version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
